# Generated by Django 5.2.4 on 2025-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_member_favorite_language_member_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='favorite_language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('C', 'C'), ('Go', 'Go'), ('Rust', 'Rust'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
