# Generated by Django 5.2.4 on 2025-08-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_test_cases_testcase'),
        ('submissions', '0002_submissionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionresult',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='submissionresult',
            name='input_data',
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.testcase'),
        ),
    ]
