# Generated by Django 5.2.4 on 2026-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_is_correct_aihintusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('java', 'Java')], max_length=10),
        ),
    ]
